baseURL = "https://wedscoop.com/"
languageCode = "en-us"
title = "Wedscoop — Wedding Photography & Films by Saurabh Kalra"
theme = "minimal-dark"

[params]
  phone = "+917982921411"
  email = "contact.wedscoop@gmail.com"
  ga = "G-RKHN2J1GX0" # GA4 ID placeholder

[taxonomies]
  tag = "tags"
  category = "categories"
  location = "locations"
  venue = "venues"
  shot = "shots"

[outputs]
  home = ["HTML","RSS","JSON"]

[build]
  writeStats = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
