name: Fetch Wedding Films

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-videos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch YouTube playlist
        run: |
          mkdir -p data
          curl -s "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=50&playlistId=${{ secrets.YT_PLAYLIST_ID }}&key=${{ secrets.YT_API_KEY }}" \
            | jq '.items[] | {title: .snippet.title, videoId: .snippet.resourceId.videoId, thumbnail: .snippet.thumbnails.medium.url}' \
            | jq -s '.' > data/weddingfilms.json
      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/weddingfilms.json
          git commit -m "Update wedding films" || echo "no changes"
          git push
